version: "3.10"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-icclh657flx&*sgq1(2$$t1&-f@cva1so1)ee-2k%4b)ka8p3%i"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: